#! /bin/bash

# usage: print_test_title repeats keyfile wordfile

function first_word {
  echo $1
}

key_wc=$(wc -l $2)
word_wc=$(wc -l $3)

key_count=$(first_word $key_wc)
word_count=$(first_word $word_wc)

echo ---------------------------------------------------------------
printf "test - %d words in container, %d lookups repeated %d times\n" \
       $word_count $key_count $1
echo ---------------------------------------------------------------



