#!/usr/bin/env bash

# check.sh -- run the uts_*.pure scripts. exit 1 on first failed script, else
# exit 0

check_file () {
  utsf=$1
  if [ -f $utsf ] ; then
    pure -x check_uts.pure $utsf
    if (( $? )) ; then 
      echo STLMAP TEST FAILURE
      exit 1; 
    fi
  fi
}

# avoid for loop to maintain desired order of execution
check_file uts_stlmap.pure
check_file uts_stlset.pure
check_file uts_stlmmap.pure
check_file uts_stlmset.pure

check_file uts_stlhmap.pure
check_file uts_stlhset.pure

check_file uts_stlmap_iter.pure
check_file uts_stlset_iter.pure
check_file uts_stlmmap_iter.pure
check_file uts_stlmset_iter.pure

check_file uts_stlmap_cache.pure
check_file uts_stlset_cache.pure

# tests passed
exit 0