#! /bin/sh

# check_script - called by make check

DESTDIR=$1

libdir=`pkg-config pure --variable libdir`
installdir=${DESTDIR}${libdir}/pure

curdir=$PWD

trap 'x=$?; rm -rf '$DESTDIR'; exit $x;' ALRM HUP INT TERM

# remove and recompile all dlls
make clean
if ! make install DESTDIR=${DESTDIR} ; then
  echo 
  echo --- MAKE CHECK FAILED ---
  exit 1
fi

# run ut for pure-stlvec
cd pure-stlvec/ut
pure -I${installdir} -L${installdir} -x ut_all.pure
stlvec_ec=$?

cd ${curdir}

echo 

# run uts for pure-stlmap
cd pure-stlmap/uts
pure -I${installdir} -L${installdir} -x check_uts.pure uts_*.pure
stlmap_ec=$?

cd ${curdir}

# clean up
rm -rf ${DESTDIR}
make clean

if [ ${stlvec_ec} -ne 0 -o ${stlmap_ec} -ne 0 ] 
then
  echo
  echo --- MAKE CHECK FAILED ---
  exit 1
fi

echo
echo --- MAKE CHECK PASSED ---
exit 0








